apiVersion: v1
kind: Service
metadata:
  labels:
    app: reverse-words
  name: reverse-words-public
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
# service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    alb.ingress.kubernetes.io/security-groups: cluster-us
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: http
    name: http
  selector:
    app: reverse-words
  type: LoadBalancer
